### ISSUE TITLE
There are large win32 build files in the repository.

### ISSUE THREAD

**Issue by boustrophedon** [SteerSuite/SteerLite#1]
https://github.com/SteerSuite/SteerLite/commit/d70ec66b690148dd74048177a9ab0445f9e8f690#diff-43d9a84ab2dd1f6d2a42626def77ba65

Files like this are windows/visual studio build artifacts and just take up unnecessary space on my hard drive. Please fix this.

SteerLite/build/win32/ is 69M alone.

This is relevant because the ilab machines have relatively small quotas and it's very easy to hit the limit.

**Comment by Neo-X** [comment]
Correct, these kinds of temporary build files should be removed from the index and added to the ignore file.

**Comment by boustrophedon** [comment]
This only partially solves the problem. Git is still storing the original files because they are there in the first commit, and therefore still part of the repository. You can see this by doing a `git checkout d70ec66b6` or simply looking here: https://github.com/SteerSuite/SteerLite/tree/d70ec66b690148dd74048177a9ab0445f9e8f690/build/win32

In order to remove the files for good from the repository, you need to use git filter-branch. http://git-scm.com/docs/git-filter-branch

However, I do not know the implications of doing so (and then force pushing to github) for all of the people who have forked the repo.
